### ISSUE TITLE
메시지 큐(Message Queue) 기능 구현

### ISSUE THREAD

**Issue by pjw1702** [opmaksim/Chat-Program#1]
+ 미니 프로젝트 주제 및 구현 목표인 채팅 프로그램의 서버 구현 부에서, 원활한 메시지 송수신을 위한 메시지 큐 기능 구현
+ 일차적으로 기본적인 기능 구현을 우선 진행하고, 차후에 멀티 스레드 기반의 데이터 통신에 적용 및 고도화할 예정

### 구현 목적

+ 멀티스레드 환경에서 여러 스레드가 동시에 작업을 수행할 때, 메시지 큐를 사용하여 스레드 간의 통신을 비동기적으로 처리하기 위함
+ 멀티 스레드 기반의 서버 프로그램에서, 서버 내의 스레드 사이에서의 메시지를 효율적이고 안전하게 주고받기 위함
+ 각 스레드는 큐에 메시지를 보내거나 받아 다른 스레드와 상호작용할 수 있음
+ 스레드가 종료되거나 예외가 발생하더라도 데이터를 잃지 않고 안정성을 높일 수 있음

#### 비동기 통신
+ 메시지 큐는 프로세스 간 비동기 통신을 지원
+ 송신자(Sender)가 메시지를 큐에 넣고 즉시 반환할 수 있어, 수신자(Receiver)가 메시지를 처리할 준비가 될 때까지 기다리지 않게 됨
+ 따라서 시스템의 응답성을 높이고, 프로세스 간의 결합도를 낮출 수 있음

#### 메시지 저장
+ 메시지 큐는 메시지를 저장할 수 있는 기능을 제공
+ 수신자가 바쁠 때도 메시지를 잃어버리지 않고 나중에 처리할 수 있음
+ 데이터 송수신의 신뢰성을 높임

#### 다중 생산자(Producer) / 소비자(Consumer)
+ 여러 프로세스가 동시에 메시지를 생성하고 소비할 수 있는 구조를 제공
+ 데이터 송수신에 대한 병렬 처리와 통신 시스템 성능이 향상 됨

 #### 동기화 및 상호작용 (Synchronization and Communication)
+ 소켓은 주로 네트워크 통신에 사용되며, 클라이언트와 서버 간의 직접적인 연결을 필요로 함
+ 송신자가 수신자가 데이터를 받을 준비가 되어야만 데이터를 전송할 수 있음
+ 반면, 메시지 큐는 송신자가 메시지를 보내고 나중에 수신자가 이를 받을 수 있도록 하는 비동기적 모델

#### 데이터 구조 (Data Structure)
+ 메시지 큐는 메시지를 큐에 넣고 뺄 수 있는 구조로 되어 있으며, 메시지의 우선 순위를 설정할 수도 있음
+ 소켓은 데이터 스트림을 기반으로 하며, 연속적인 바이트 스트림(배열 형태의 버퍼)으로 데이터를 전송

#### 신뢰성 (Reliability)
+ 메시지 큐는 메시지를 잃지 않도록 보장하는 메커니즘을 제공
+ 데이터가 소켓을 통해 전송되는 경우, 패킷 손실이나 연결 끊김 등의 문제로 인해 데이터가 손실될 수 있음

### Task
- [ ] systemV 기반의 메시지 큐 기능 구현
- [ ] POSIX 기반의 메시지 큐 기능 구현 
- [ ] 메시지 큐 작동 테스트

### Reference
+
